### ISSUE TITLE
Hop vs Lightspeed (and others) -- and question about dot-repeat

### ISSUE THREAD

**Issue by megalithic** [akinsho/dotfiles#10]
https://github.com/akinsho/dotfiles/blob/c84abbec12ff23a3e068ae3ecc6202f212fb7800/.config/nvim/lua/as/plugins/hop.lua#L2

Hey there @akinsho ..

I've been flipping between lightspeed.nvim and hop.nvim; both have interesting usages and features; hop is presently my preferred, however, hop doesn't have dot-repeat. Have you managed to work around that in any sort of way? 

Thanks for your time!

**Comment by akinsho** [comment]
Hi @megalithic,

So I've never tried lightspeed actually, just never really seen the need, I find the readme a little too involved in clearly explaining in a concise way why it was potentially better. Re dot repeat tbh I've never really noticed the absence. I actually just use the native search with n/N a lot and only use hop once in a while to go to a precise location which isn't something I often need to repeat. What would you be trying to dot repeat?

**Comment by megalithic** [comment]
Thanks kindly for the response..

I'll typically do something like `/someword`, then `dt(`, then `n`, then `.`.

So basically, basic motions to do on a thing where honestly, I should be using macros, but just end up doing the ole, `n`, `.` sequence.

**Comment by akinsho** [comment]
Ah I see, makes sense. At the moment I use multi cursors for those kinds of edits, or otherwise I have a `cq` mapping that reproduce an edit in the next occurrence, so I use `cq` ⇾ `dt(` then ⇾ `<CR>` will carry it out at the next occurrence.

**Comment by megalithic** [comment]
That's good info, much thanks. I had never used multi-word cursors before so, it's not even in my purview. I'll look around your config to see how/what you use for that. 

Thanks again for your repo, it's been an incredible wealth of knowledge and inspiration of all sorts
