### ISSUE TITLE
Question around packer config + "attempt to index upvalue" errors

### ISSUE THREAD

**Issue by megalithic** [akinsho/dotfiles#12]
https://github.com/akinsho/dotfiles/blob/4a3ea62f7cd632e5c2561c50113c6e7d2a6e5b20/.config/nvim/lua/as/plugins/init.lua#L262

Good day @akinsho!

How have you gotten around allowing access, in packer config functions, your global objects (as in your case, `as.*`)?

I didn't see anything obvious in your config, other than hoisting the declaration and assignment to your .config/nvim/init.lua (and not inside of your globals.lua)?

**Comment by akinsho** [comment]
@megalithic not entirely sure that I understand but as you've already alluded to you can use global variables inside of packer functions which is one of the use cases of the global namespace.

**Comment by megalithic** [comment]
Apologies for the long delay.

Packer is still angered at upvalues: `Error running config for mason.nvim: [string "..."]:0: attempt to index upvalue '' (a nil value)` when attempting to access my `_G.foo` variable that carries the majority of utility functions and other items.

It seems like you aren't doing anything sneaky in your config other than just assigning `_G.as = ...` and then just accessing in your config `as.<...>`. 

Anywho, thanks for responding, I'll keep digging.
