### ISSUE TITLE
Neovim cursor location bellow bufferline

### ISSUE THREAD

**Issue by Thlr** [akinsho/dotfiles#17]
Hi @akinsho , first of all thank you very much for the very cool neovim configuration that I am having fun exploring, and for the bufferline plugin as well that I am just trying out.

I noticed in your screenshots that you have the exact cursor location (file path followed by the location in the code) printed just bellow your bufferline, which I find very convenient and that I would love having myself.

Although, I haven't been able to see where in your files this line is defined.

I would appreciate any help :)

**Comment by akinsho** [comment]
Thanks @Thlr, it's a winbar provided by a plugin called dropbar.nvim
