### ISSUE TITLE
No  padding around Vertsplit 

### ISSUE THREAD

**Issue by siduck** [akinsho/dotfiles#3]
@akinsho Hi , how did you get no space / padding around the vertsplit? I have some weird padding around the vertsplit . Look :

![image](https://user-images.githubusercontent.com/59060246/117408319-6488ad00-af2d-11eb-914d-7fe3d7f38821.png)

and yours look much better :D 

![image](https://user-images.githubusercontent.com/59060246/117408352-72d6c900-af2d-11eb-9985-80bf636cd1df.png)

**Comment by akinsho** [comment]
Hi, @siduck76 this repo isn't really intended for people raising issues and asking questions etc. I'm happy for people to look through my dotfiles for inspiration etc. but I really don't want to start having to deal with questions about specific parts of it.

You can get the vert split to behave like I have by using a right or left aligned box drawing character (you can find them if you google box drawing character). Then you have to set the vertical split `fillchar`
