### ISSUE TITLE
Help with keybinding 🙏🏼 

### ISSUE THREAD

**Issue by corpooo** [akinsho/dotfiles#5]
Hi, I pretty much love your config and I find it very inspiring.

In your `mappings.lua` file you have this set up:
```
local function execute_macro_over_visual_range()
  vim.cmd [[echo "@".getcmdline()]]
  vim.cmd [[":'<,'>normal @".nr2char(getchar())]]
end

xnoremap("@", execute_macro_over_visual_range)
```

But I just can't get it to work.. If I press `@` in visual mode, the `@` is printed in the command line, but the next key just won't read.

It you have any idea why this is happening, I would really apreciate your help

Thanks and have a nice day!

**Comment by akinsho** [comment]
@andreicorpo this original source of that snippet is https://github.com/stoeffel/.dotfiles/blob/master/vim/visual-at.vim
who has excellent dotfiles. Tbh I never really tested it when I converted to lua and it doesn't work as is. If you just want to get it working without faff I recommend just doing.
```lua
vim.cmd [[
xnoremap @ :<C-u>call ExecuteMacroOverVisualRange()<CR>

function! ExecuteMacroOverVisualRange()
  echo "@".getcmdline()
  execute ":'<,'>normal @".nr2char(getchar())
endfunction
]]
```
I'll get it working one day but it's not really a priority for me at the moment tbh 🤷🏾‍♂️

**Comment by RaZ0rr-Two** [comment]
Sorry for bumping this , maybe this might be useful

```lua
-----------------------------------------------------------------------------//
-- Capitalize toggle
-----------------------------------------------------------------------------//
nnoremap('<leader><c-u>', 'viw~<esc>`]')
```

**Comment by akinsho** [comment]
@RaZ0rr-Two not sure how the mapping you have posted above relates to the one in this issue tbh

**Comment by RaZ0rr-Two** [comment]
It doesn't relate at all. If anything, the only relation is

> Hi, I pretty much love your config and I find it very inspiring.

So, just putting it there incase you find it useful.
