### ISSUE TITLE
Curious of your use cases for orgmode.nvim and more..

### ISSUE THREAD

**Issue by megalithic** [akinsho/dotfiles#7]
Hey there @akinsho!

Your config is always such a wealth of valuable info. I've recently found orgmode.nvim (I've been a user of tooling around zettelkasten for the few months), and would _love_ to see how you go about using orgmode.nvim; your use cases for it, etc. Not only that, I'd _really_ love to see your dotfiles setup in action. Ever thought about youtube vids, or twitch?

Thanks for the inspiration and all you do for the community!

**Comment by akinsho** [comment]
Hi @megalithic,

thanks for the kind words 😄, glad it's proven useful. Re. orgmode tbh I use it pretty similarly to almost anyone else i.e. I don't think I do anything particularly novel with it. I watch a lot of systemcrafters emacs youtube videos and the author spends a bit of time going over using org which I find useful. I primarily use it to organize work I have to do across, my personal projects, my open source projects and my actual job.

Re. doing something like YouTube or twitch tbh not sure if I have the time or temperament for that, but you never know 🤷🏿‍♂️

**Comment by ferdinandsalis** [comment]
I just wanna chime in here and say that I too would be interested in seeing your setup in action.

Of course I understand if you don't have the time. Though a mere live coding session with key capture while you you are working on your dot files would do ☺️. No need for narration. Just an over the shoulder kinda thing …

If you ever find the muse just let us know here. In the mean time thanks for sharing and all the best.

**Comment by megalithic** [comment]
Just circling back here; I took your nvim config for a spin and my oh my, what you have built for yourself is magnificent. Bravo sir!
