### ISSUE TITLE
Do your multiple cursor mappings work in Neovim?

### ISSUE THREAD

**Issue by olimorris** [akinsho/dotfiles#9]
Always keep an eye on your dotfiles to see if you're sprinkling any magic in Neovim that I can "borrow" :wink:.

I notice in your [mapping file](https://github.com/akinsho/dotfiles/blob/45c4c17084d0aa572e52cc177ac5b9d6db1585ae/.config/nvim/plugin/mappings.lua#L309) you've implemented a lot of the great work from this [article](http://www.kevinli.co/posts/2017-01-19-multiple-cursors-in-500-bytes-of-vimscript/). I'd tried a year ago to implement and failed (was just migrating config to Lua then).

I've just tried implementing your mappings and whenever I try and replace over a selection and press `cq` I just get it dumping the value of `vim.g.mc` into the command line:

![Screen Shot 2022-03-13 at 10 45 48@2x](https://user-images.githubusercontent.com/9512444/158055958-bf73112e-fcc9-4b3f-954b-574f647ef838.png)

Anyway, wondered if it works for you or if I'm getting too excited 😄 .

**Comment by akinsho** [comment]
Hi @olimorris 👋🏿 , that mapping is actually broken, I need to finally commit to fixing or deleting it. It used to work in vimscript, but something is missing/wrong about how I've migrated it to Lua, and it doesn't really work any more 😭 I've just been too lazy to deal with it. I also tend to use `vim-visual-multi` a lot nowadays and rarely use that mapping

**Comment by olimorris** [comment]
It's been on my list of things to investigate for a while, as well. I've been using the the `change word` mappings quite a bit today and they're so slick.

Have your latest commits worked? I'll try and take a look tonight too.

**Comment by olimorris** [comment]
So changing `vim.g.mc` to this:
```lua
vim.g.mc = vim.api.nvim_replace_termcodes([[y/\V<C-r>=escape(@", '/')<CR><CR>]], true, true, true)
```

has unlocked these bindings for me:

```lua
vim.api.nvim_set_keymap("x", "cn", [[g:mc . "``cgn"]], { expr = true, silent = true })
vim.api.nvim_set_keymap("x", "cN", [[g:mc . "``cgN"]], { expr = true, silent = true })
```

but the `cq` and `cQ` ones still seem to be failing.

**Comment by akinsho** [comment]
@olimorris you should have a look at the most recent version of the file I force pushed some changes you might have missed. I now have it all working with the replace termcodes suggestion 🚀 🥇 good call.

**Comment by olimorris** [comment]
Amazing! I've had some issues getting the macro to work as per the tutorial but replacing over a search range works like a dream which was pretty much all I ever used a multi-cursor for anyway. Thanks for your help.
